version: "3"
services:

  # Edgebox Web Service (Reverse Proxy)
  proxy:
    image: nginx
    restart : always
    # maps config file into the proxy container
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./error_pages:/usr/share/nginx/html/
    ports:
      - 80:80
    links:
      - api

  # API Service
  api:
    build:  ../api
    restart: always

  # -- EDGEAPPS CONFIG --
