##################################
# Edgebox ws proxy configuration
##################################

# Detect original scheme from Cloudflare CF-Visitor header
map $http_cf_visitor $real_scheme {
    ~*https   https;
    default   $scheme;
}

map $real_scheme $real_ssl {
    https     on;
    default   off;
}

map $real_scheme $real_port {
    https     443;
    default   80;
}

# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $real_scheme;
proxy_set_header X-Forwarded-Ssl $real_ssl;
proxy_set_header X-Forwarded-Port $real_port;
client_max_body_size 10G;
client_body_buffer_size 400M;

# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";

server {

        server_name localhost;

        location = / {
                if (-f /usr/share/nginx/html/installing.html) {
                        return 503;
                }
        }

        location = /installing.html {
                root /usr/share/nginx/html;
        }

        location = /style.css {
                root /usr/share/nginx/html;
        }
        
        location = /crest.png {
                root /usr/share/nginx/html;
        }

        location = /script.js {
                root /usr/share/nginx/html;
        }

        error_page 404 /proxy_404.html;
        location = /proxy_404.html {
                root /usr/share/nginx/html;
                internal;
        }

        error_page 500 502 504 /proxy_50x.html;
        location = /proxy_50x.html {
                root /usr/share/nginx/html;
                internal;
        }

        error_page 503 /proxy_installing.html;
        location = /proxy_installing.html {
                root /usr/share/nginx/html;
                internal;
        }

}
