name: Edgebox ws Update Notification
on:
  push:
    branches: 
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: An update to the ws (web service) repository was made via ${{ github.event_name }} merge by ${{github.actor}} - ${{ github.event.head_commit.message }}. Full changes in https://github.com/edgebox-iot/ws/commit/${{github.sha}}
